//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.19 at 11:07:17 AM BST 
//

package com.google.earth.kml._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for IconStyleType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;IconStyleType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.1}ColorStyleType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;scale&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}float&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;heading&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}float&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;Icon&quot; type=&quot;{http://earth.google.com/kml/2.1}IconStyleIconType&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;hotSpot&quot; type=&quot;{http://earth.google.com/kml/2.1}vec2Type&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IconStyleType", propOrder = { "scale", "heading", "icon",
    "hotSpot" })
@SuppressWarnings("all")
public class IconStyleType extends ColorStyleType {

  @XmlElement(defaultValue = "1")
  protected Float scale;

  @XmlElement(defaultValue = "0")
  protected Float heading;

  @XmlElement(name = "Icon")
  protected IconStyleIconType icon;

  protected Vec2Type hotSpot;

  /**
   * Gets the value of the scale property.
   * 
   * @return possible object is {@link Float }
   * 
   */
  public Float getScale() {
    return scale;
  }

  /**
   * Sets the value of the scale property.
   * 
   * @param value
   *          allowed object is {@link Float }
   * 
   */
  public void setScale(Float value) {
    this.scale = value;
  }

  /**
   * Gets the value of the heading property.
   * 
   * @return possible object is {@link Float }
   * 
   */
  public Float getHeading() {
    return heading;
  }

  /**
   * Sets the value of the heading property.
   * 
   * @param value
   *          allowed object is {@link Float }
   * 
   */
  public void setHeading(Float value) {
    this.heading = value;
  }

  /**
   * Gets the value of the icon property.
   * 
   * @return possible object is {@link IconStyleIconType }
   * 
   */
  public IconStyleIconType getIcon() {
    return icon;
  }

  /**
   * Sets the value of the icon property.
   * 
   * @param value
   *          allowed object is {@link IconStyleIconType }
   * 
   */
  public void setIcon(IconStyleIconType value) {
    this.icon = value;
  }

  /**
   * Gets the value of the hotSpot property.
   * 
   * @return possible object is {@link Vec2Type }
   * 
   */
  public Vec2Type getHotSpot() {
    return hotSpot;
  }

  /**
   * Sets the value of the hotSpot property.
   * 
   * @param value
   *          allowed object is {@link Vec2Type }
   * 
   */
  public void setHotSpot(Vec2Type value) {
    this.hotSpot = value;
  }

}
