//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.19 at 11:07:17 AM BST 
//

package com.google.earth.kml._2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * <p>
 * Java class for itemIconStateEnum.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name=&quot;itemIconStateEnum&quot;&gt;
 *   &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;&gt;
 *     &lt;enumeration value=&quot;open&quot;/&gt;
 *     &lt;enumeration value=&quot;closed&quot;/&gt;
 *     &lt;enumeration value=&quot;error&quot;/&gt;
 *     &lt;enumeration value=&quot;fetching0&quot;/&gt;
 *     &lt;enumeration value=&quot;fetching1&quot;/&gt;
 *     &lt;enumeration value=&quot;fetching2&quot;/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlEnum
@SuppressWarnings("all")
public enum ItemIconStateEnum {

  @XmlEnumValue("open")
  OPEN("open"), @XmlEnumValue("closed")
  CLOSED("closed"), @XmlEnumValue("error")
  ERROR("error"), @XmlEnumValue("fetching0")
  FETCHING_0("fetching0"), @XmlEnumValue("fetching1")
  FETCHING_1("fetching1"), @XmlEnumValue("fetching2")
  FETCHING_2("fetching2");
  private final String value;

  ItemIconStateEnum(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static ItemIconStateEnum fromValue(String v) {
    for (ItemIconStateEnum c : ItemIconStateEnum.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v.toString());
  }

}
