//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.19 at 11:07:17 AM BST 
//

package com.google.earth.kml._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for LatLonBoxType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;LatLonBoxType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.1}ObjectType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;north&quot; type=&quot;{http://earth.google.com/kml/2.1}angle180&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;south&quot; type=&quot;{http://earth.google.com/kml/2.1}angle180&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;east&quot; type=&quot;{http://earth.google.com/kml/2.1}angle180&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;west&quot; type=&quot;{http://earth.google.com/kml/2.1}angle180&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;rotation&quot; type=&quot;{http://earth.google.com/kml/2.1}angle180&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LatLonBoxType", propOrder = { "north", "south", "east",
    "west", "rotation" })
@SuppressWarnings("all")
public class LatLonBoxType extends ObjectType {

  @XmlElement(defaultValue = "180.0")
  protected Double north;

  @XmlElement(defaultValue = "-180.0")
  protected Double south;

  @XmlElement(defaultValue = "180.0")
  protected Double east;

  @XmlElement(defaultValue = "-180.0")
  protected Double west;

  @XmlElement(defaultValue = "0")
  protected Double rotation;

  /**
   * Gets the value of the north property.
   * 
   * @return possible object is {@link Double }
   * 
   */
  public Double getNorth() {
    return north;
  }

  /**
   * Sets the value of the north property.
   * 
   * @param value
   *          allowed object is {@link Double }
   * 
   */
  public void setNorth(Double value) {
    this.north = value;
  }

  /**
   * Gets the value of the south property.
   * 
   * @return possible object is {@link Double }
   * 
   */
  public Double getSouth() {
    return south;
  }

  /**
   * Sets the value of the south property.
   * 
   * @param value
   *          allowed object is {@link Double }
   * 
   */
  public void setSouth(Double value) {
    this.south = value;
  }

  /**
   * Gets the value of the east property.
   * 
   * @return possible object is {@link Double }
   * 
   */
  public Double getEast() {
    return east;
  }

  /**
   * Sets the value of the east property.
   * 
   * @param value
   *          allowed object is {@link Double }
   * 
   */
  public void setEast(Double value) {
    this.east = value;
  }

  /**
   * Gets the value of the west property.
   * 
   * @return possible object is {@link Double }
   * 
   */
  public Double getWest() {
    return west;
  }

  /**
   * Sets the value of the west property.
   * 
   * @param value
   *          allowed object is {@link Double }
   * 
   */
  public void setWest(Double value) {
    this.west = value;
  }

  /**
   * Gets the value of the rotation property.
   * 
   * @return possible object is {@link Double }
   * 
   */
  public Double getRotation() {
    return rotation;
  }

  /**
   * Sets the value of the rotation property.
   * 
   * @param value
   *          allowed object is {@link Double }
   * 
   */
  public void setRotation(Double value) {
    this.rotation = value;
  }

}
