//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.19 at 11:07:17 AM BST 
//

package com.google.earth.kml._2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * <p>
 * Java class for listItemTypeEnum.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name=&quot;listItemTypeEnum&quot;&gt;
 *   &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;&gt;
 *     &lt;enumeration value=&quot;radioFolder&quot;/&gt;
 *     &lt;enumeration value=&quot;check&quot;/&gt;
 *     &lt;enumeration value=&quot;checkHideChildren&quot;/&gt;
 *     &lt;enumeration value=&quot;checkOffOnly&quot;/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlEnum
@SuppressWarnings("all")
public enum ListItemTypeEnum {

  @XmlEnumValue("radioFolder")
  RADIO_FOLDER("radioFolder"), @XmlEnumValue("check")
  CHECK("check"), @XmlEnumValue("checkHideChildren")
  CHECK_HIDE_CHILDREN("checkHideChildren"), @XmlEnumValue("checkOffOnly")
  CHECK_OFF_ONLY("checkOffOnly");
  private final String value;

  ListItemTypeEnum(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static ListItemTypeEnum fromValue(String v) {
    for (ListItemTypeEnum c : ListItemTypeEnum.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v.toString());
  }

}
