//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.19 at 11:07:17 AM BST 
//

package com.google.earth.kml._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for ListStyleType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;ListStyleType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.1}ObjectType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;listItemType&quot; type=&quot;{http://earth.google.com/kml/2.1}listItemTypeEnum&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;bgColor&quot; type=&quot;{http://earth.google.com/kml/2.1}color&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;ItemIcon&quot; type=&quot;{http://earth.google.com/kml/2.1}ItemIconType&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListStyleType", propOrder = { "listItemType", "bgColor",
    "itemIcon" })
@SuppressWarnings("all")
public class ListStyleType extends ObjectType {

  @XmlElement(defaultValue = "check")
  protected ListItemTypeEnum listItemType;

  @XmlElement(type = String.class, defaultValue = "ffffffff")
  @XmlJavaTypeAdapter(HexBinaryAdapter.class)
  protected byte[] bgColor;

  @XmlElement(name = "ItemIcon")
  protected List<ItemIconType> itemIcon;

  /**
   * Gets the value of the listItemType property.
   * 
   * @return possible object is {@link ListItemTypeEnum }
   * 
   */
  public ListItemTypeEnum getListItemType() {
    return listItemType;
  }

  /**
   * Sets the value of the listItemType property.
   * 
   * @param value
   *          allowed object is {@link ListItemTypeEnum }
   * 
   */
  public void setListItemType(ListItemTypeEnum value) {
    this.listItemType = value;
  }

  /**
   * Gets the value of the bgColor property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public byte[] getBgColor() {
    return bgColor;
  }

  /**
   * Sets the value of the bgColor property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setBgColor(byte[] value) {
    this.bgColor = ((byte[]) value);
  }

  /**
   * Gets the value of the itemIcon property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE>
   * method for the itemIcon property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getItemIcon().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link ItemIconType }
   * 
   * 
   */
  public List<ItemIconType> getItemIcon() {
    if (itemIcon == null) {
      itemIcon = new ArrayList<ItemIconType>();
    }
    return this.itemIcon;
  }

}
