//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.19 at 11:07:17 AM BST 
//

package com.google.earth.kml._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for LodType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;LodType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.1}ObjectType&quot;&gt;
 *       &lt;all&gt;
 *         &lt;element name=&quot;minLodPixels&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}float&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;maxLodPixels&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}float&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;minFadeExtent&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}float&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;maxFadeExtent&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}float&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/all&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LodType", propOrder = { "minLodPixels", "maxLodPixels",
    "minFadeExtent", "maxFadeExtent" })
@SuppressWarnings("all")
public class LodType extends ObjectType {

  @XmlElement(defaultValue = "0")
  protected Float minLodPixels;

  @XmlElement(defaultValue = "-1")
  protected Float maxLodPixels;

  @XmlElement(defaultValue = "0")
  protected Float minFadeExtent;

  @XmlElement(defaultValue = "0")
  protected Float maxFadeExtent;

  /**
   * Gets the value of the minLodPixels property.
   * 
   * @return possible object is {@link Float }
   * 
   */
  public Float getMinLodPixels() {
    return minLodPixels;
  }

  /**
   * Sets the value of the minLodPixels property.
   * 
   * @param value
   *          allowed object is {@link Float }
   * 
   */
  public void setMinLodPixels(Float value) {
    this.minLodPixels = value;
  }

  /**
   * Gets the value of the maxLodPixels property.
   * 
   * @return possible object is {@link Float }
   * 
   */
  public Float getMaxLodPixels() {
    return maxLodPixels;
  }

  /**
   * Sets the value of the maxLodPixels property.
   * 
   * @param value
   *          allowed object is {@link Float }
   * 
   */
  public void setMaxLodPixels(Float value) {
    this.maxLodPixels = value;
  }

  /**
   * Gets the value of the minFadeExtent property.
   * 
   * @return possible object is {@link Float }
   * 
   */
  public Float getMinFadeExtent() {
    return minFadeExtent;
  }

  /**
   * Sets the value of the minFadeExtent property.
   * 
   * @param value
   *          allowed object is {@link Float }
   * 
   */
  public void setMinFadeExtent(Float value) {
    this.minFadeExtent = value;
  }

  /**
   * Gets the value of the maxFadeExtent property.
   * 
   * @return possible object is {@link Float }
   * 
   */
  public Float getMaxFadeExtent() {
    return maxFadeExtent;
  }

  /**
   * Sets the value of the maxFadeExtent property.
   * 
   * @param value
   *          allowed object is {@link Float }
   * 
   */
  public void setMaxFadeExtent(Float value) {
    this.maxFadeExtent = value;
  }

}
