//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.19 at 11:07:17 AM BST 
//

package com.google.earth.kml._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for NetworkLinkType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;NetworkLinkType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.1}FeatureType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;refreshVisibility&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}boolean&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;flyToView&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}boolean&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;choice minOccurs=&quot;0&quot;&gt;
 *           &lt;element ref=&quot;{http://earth.google.com/kml/2.1}Link&quot;/&gt;
 *           &lt;element name=&quot;Url&quot; type=&quot;{http://earth.google.com/kml/2.1}LinkType&quot;/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkLinkType", propOrder = { "refreshVisibility",
    "flyToView", "link", "url" })
@SuppressWarnings("all")
public class NetworkLinkType extends FeatureType {

  @XmlElement(defaultValue = "0")
  protected Boolean refreshVisibility;

  @XmlElement(defaultValue = "0")
  protected Boolean flyToView;

  @XmlElement(name = "Link")
  protected LinkType link;

  @XmlElement(name = "Url")
  protected LinkType url;

  /**
   * Gets the value of the refreshVisibility property.
   * 
   * @return possible object is {@link Boolean }
   * 
   */
  public Boolean isRefreshVisibility() {
    return refreshVisibility;
  }

  /**
   * Sets the value of the refreshVisibility property.
   * 
   * @param value
   *          allowed object is {@link Boolean }
   * 
   */
  public void setRefreshVisibility(Boolean value) {
    this.refreshVisibility = value;
  }

  /**
   * Gets the value of the flyToView property.
   * 
   * @return possible object is {@link Boolean }
   * 
   */
  public Boolean isFlyToView() {
    return flyToView;
  }

  /**
   * Sets the value of the flyToView property.
   * 
   * @param value
   *          allowed object is {@link Boolean }
   * 
   */
  public void setFlyToView(Boolean value) {
    this.flyToView = value;
  }

  /**
   * Gets the value of the link property.
   * 
   * @return possible object is {@link LinkType }
   * 
   */
  public LinkType getLink() {
    return link;
  }

  /**
   * Sets the value of the link property.
   * 
   * @param value
   *          allowed object is {@link LinkType }
   * 
   */
  public void setLink(LinkType value) {
    this.link = value;
  }

  /**
   * Gets the value of the url property.
   * 
   * @return possible object is {@link LinkType }
   * 
   */
  public LinkType getUrl() {
    return url;
  }

  /**
   * Sets the value of the url property.
   * 
   * @param value
   *          allowed object is {@link LinkType }
   * 
   */
  public void setUrl(LinkType value) {
    this.url = value;
  }

}
