//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.19 at 11:07:17 AM BST 
//

package com.google.earth.kml._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for OverlayType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;OverlayType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.1}FeatureType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;color&quot; type=&quot;{http://earth.google.com/kml/2.1}color&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;drawOrder&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}int&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.1}Icon&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OverlayType", propOrder = { "color", "drawOrder", "icon" })
@SuppressWarnings("all")
public abstract class OverlayType extends FeatureType {

  @XmlElement(type = String.class, defaultValue = "ffffffff")
  @XmlJavaTypeAdapter(HexBinaryAdapter.class)
  protected byte[] color;

  @XmlElement(defaultValue = "0")
  protected Integer drawOrder;

  @XmlElement(name = "Icon")
  protected LinkType icon;

  /**
   * Gets the value of the color property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public byte[] getColor() {
    return color;
  }

  /**
   * Sets the value of the color property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setColor(byte[] value) {
    this.color = ((byte[]) value);
  }

  /**
   * Gets the value of the drawOrder property.
   * 
   * @return possible object is {@link Integer }
   * 
   */
  public Integer getDrawOrder() {
    return drawOrder;
  }

  /**
   * Sets the value of the drawOrder property.
   * 
   * @param value
   *          allowed object is {@link Integer }
   * 
   */
  public void setDrawOrder(Integer value) {
    this.drawOrder = value;
  }

  /**
   * Gets the value of the icon property.
   * 
   * @return possible object is {@link LinkType }
   * 
   */
  public LinkType getIcon() {
    return icon;
  }

  /**
   * Sets the value of the icon property.
   * 
   * @param value
   *          allowed object is {@link LinkType }
   * 
   */
  public void setIcon(LinkType value) {
    this.icon = value;
  }

}
