//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.19 at 11:07:17 AM BST 
//

package com.google.earth.kml._2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PlacemarkType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;PlacemarkType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.1}FeatureType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.1}Geometry&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlacemarkType", propOrder = { "geometry" })
@SuppressWarnings("all")
public class PlacemarkType extends FeatureType {

  @XmlElementRef(name = "Geometry", namespace = "http://earth.google.com/kml/2.1", type = JAXBElement.class)
  protected JAXBElement<? extends GeometryType> geometry;

  /**
   * Gets the value of the geometry property.
   * 
   * @return possible object is {@link JAXBElement }{@code <}{@link GeometryType }{@code >}
   *         {@link JAXBElement }{@code <}{@link MultiGeometryType }{@code >}
   *         {@link JAXBElement }{@code <}{@link LineStringType }{@code >}
   *         {@link JAXBElement }{@code <}{@link LinearRingType }{@code >}
   *         {@link JAXBElement }{@code <}{@link PointType }{@code >}
   *         {@link JAXBElement }{@code <}{@link PolygonType }{@code >}
   *         {@link JAXBElement }{@code <}{@link ModelType }{@code >}
   * 
   */
  public JAXBElement<? extends GeometryType> getGeometry() {
    return geometry;
  }

  /**
   * Sets the value of the geometry property.
   * 
   * @param value
   *          allowed object is {@link JAXBElement }{@code <}{@link GeometryType }{@code >}
   *          {@link JAXBElement }{@code <}{@link MultiGeometryType }{@code >}
   *          {@link JAXBElement }{@code <}{@link LineStringType }{@code >}
   *          {@link JAXBElement }{@code <}{@link LinearRingType }{@code >}
   *          {@link JAXBElement }{@code <}{@link PointType }{@code >}
   *          {@link JAXBElement }{@code <}{@link PolygonType }{@code >}
   *          {@link JAXBElement }{@code <}{@link ModelType }{@code >}
   * 
   */
  public void setGeometry(JAXBElement<? extends GeometryType> value) {
    this.geometry = ((JAXBElement<? extends GeometryType>) value);
  }

}
