//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.19 at 11:07:17 AM BST 
//

package com.google.earth.kml._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ScaleType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;ScaleType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.1}ObjectType&quot;&gt;
 *       &lt;all&gt;
 *         &lt;element name=&quot;x&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}double&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;y&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}double&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;z&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}double&quot; minOccurs=&quot;0&quot;/&gt;
 *       &lt;/all&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScaleType", propOrder = { "x", "y", "z" })
@SuppressWarnings("all")
public class ScaleType extends ObjectType {

  @XmlElement(defaultValue = "1.0")
  protected Double x;

  @XmlElement(defaultValue = "1.0")
  protected Double y;

  @XmlElement(defaultValue = "1.0")
  protected Double z;

  /**
   * Gets the value of the x property.
   * 
   * @return possible object is {@link Double }
   * 
   */
  public Double getX() {
    return x;
  }

  /**
   * Sets the value of the x property.
   * 
   * @param value
   *          allowed object is {@link Double }
   * 
   */
  public void setX(Double value) {
    this.x = value;
  }

  /**
   * Gets the value of the y property.
   * 
   * @return possible object is {@link Double }
   * 
   */
  public Double getY() {
    return y;
  }

  /**
   * Sets the value of the y property.
   * 
   * @param value
   *          allowed object is {@link Double }
   * 
   */
  public void setY(Double value) {
    this.y = value;
  }

  /**
   * Gets the value of the z property.
   * 
   * @return possible object is {@link Double }
   * 
   */
  public Double getZ() {
    return z;
  }

  /**
   * Sets the value of the z property.
   * 
   * @param value
   *          allowed object is {@link Double }
   * 
   */
  public void setZ(Double value) {
    this.z = value;
  }

}
