//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.19 at 11:07:17 AM BST 
//

package com.google.earth.kml._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for StyleMapPairType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;StyleMapPairType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;all&gt;
 *         &lt;element name=&quot;key&quot; type=&quot;{http://earth.google.com/kml/2.1}styleStateEnum&quot;/&gt;
 *         &lt;element ref=&quot;{http://earth.google.com/kml/2.1}styleUrl&quot;/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StyleMapPairType", propOrder = {

})
@SuppressWarnings("all")
public class StyleMapPairType {

  @XmlElement(required = true)
  protected StyleStateEnum key;

  @XmlElement(required = true)
  protected String styleUrl;

  /**
   * Gets the value of the key property.
   * 
   * @return possible object is {@link StyleStateEnum }
   * 
   */
  public StyleStateEnum getKey() {
    return key;
  }

  /**
   * Sets the value of the key property.
   * 
   * @param value
   *          allowed object is {@link StyleStateEnum }
   * 
   */
  public void setKey(StyleStateEnum value) {
    this.key = value;
  }

  /**
   * Gets the value of the styleUrl property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getStyleUrl() {
    return styleUrl;
  }

  /**
   * Sets the value of the styleUrl property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setStyleUrl(String value) {
    this.styleUrl = value;
  }

}
