//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.19 at 11:07:17 AM BST 
//

package com.google.earth.kml._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for TimeStampType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;TimeStampType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base=&quot;{http://earth.google.com/kml/2.1}TimePrimitiveType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;when&quot; type=&quot;{http://earth.google.com/kml/2.1}dateTimeType&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeStampType", propOrder = { "when" })
@SuppressWarnings("all")
public class TimeStampType extends TimePrimitiveType {

  @XmlElement(required = true)
  protected String when;

  /**
   * Gets the value of the when property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getWhen() {
    return when;
  }

  /**
   * Sets the value of the when property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setWhen(String value) {
    this.when = value;
  }

}
