//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.19 at 11:07:17 AM BST 
//

package com.google.earth.kml._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for UpdateType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;UpdateType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;targetHref&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}anyURI&quot;/&gt;
 *         &lt;choice maxOccurs=&quot;unbounded&quot;&gt;
 *           &lt;element name=&quot;Create&quot; type=&quot;{http://earth.google.com/kml/2.1}CreateType&quot; minOccurs=&quot;0&quot;/&gt;
 *           &lt;element name=&quot;Delete&quot; type=&quot;{http://earth.google.com/kml/2.1}DeleteType&quot; minOccurs=&quot;0&quot;/&gt;
 *           &lt;element name=&quot;Change&quot; type=&quot;{http://earth.google.com/kml/2.1}ChangeType&quot; minOccurs=&quot;0&quot;/&gt;
 *           &lt;element name=&quot;Replace&quot; type=&quot;{http://earth.google.com/kml/2.1}ReplaceType&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateType", propOrder = { "targetHref",
    "createOrDeleteOrChange" })
@SuppressWarnings("all")
public class UpdateType {

  @XmlElement(required = true)
  protected String targetHref;

  @XmlElements( { @XmlElement(name = "Replace", type = ReplaceType.class),
      @XmlElement(name = "Change", type = ChangeType.class),
      @XmlElement(name = "Create", type = CreateType.class),
      @XmlElement(name = "Delete", type = DeleteType.class) })
  protected List<Object> createOrDeleteOrChange;

  /**
   * Gets the value of the targetHref property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getTargetHref() {
    return targetHref;
  }

  /**
   * Sets the value of the targetHref property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setTargetHref(String value) {
    this.targetHref = value;
  }

  /**
   * Gets the value of the createOrDeleteOrChange property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE>
   * method for the createOrDeleteOrChange property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getCreateOrDeleteOrChange().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link ReplaceType } {@link ChangeType } {@link CreateType }
   * {@link DeleteType }
   * 
   * 
   */
  public List<Object> getCreateOrDeleteOrChange() {
    if (createOrDeleteOrChange == null) {
      createOrDeleteOrChange = new ArrayList<Object>();
    }
    return this.createOrDeleteOrChange;
  }

}
