//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.19 at 11:07:17 AM BST 
//

package com.google.earth.kml._2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * <p>
 * Java class for viewRefreshModeEnum.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name=&quot;viewRefreshModeEnum&quot;&gt;
 *   &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;&gt;
 *     &lt;enumeration value=&quot;never&quot;/&gt;
 *     &lt;enumeration value=&quot;onRequest&quot;/&gt;
 *     &lt;enumeration value=&quot;onStop&quot;/&gt;
 *     &lt;enumeration value=&quot;onRegion&quot;/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlEnum
@SuppressWarnings("all")
public enum ViewRefreshModeEnum {

  @XmlEnumValue("never")
  NEVER("never"), @XmlEnumValue("onRequest")
  ON_REQUEST("onRequest"), @XmlEnumValue("onStop")
  ON_STOP("onStop"), @XmlEnumValue("onRegion")
  ON_REGION("onRegion");
  private final String value;

  ViewRefreshModeEnum(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static ViewRefreshModeEnum fromValue(String v) {
    for (ViewRefreshModeEnum c : ViewRefreshModeEnum.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v.toString());
  }

}
