//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.30 at 12:41:51 PM BST 
//

package com.topografix.gpx._1._0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for boundsType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;boundsType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;attribute name=&quot;maxlat&quot; use=&quot;required&quot; type=&quot;{http://www.topografix.com/GPX/1/0}latitudeType&quot; /&gt;
 *       &lt;attribute name=&quot;maxlon&quot; use=&quot;required&quot; type=&quot;{http://www.topografix.com/GPX/1/0}longitudeType&quot; /&gt;
 *       &lt;attribute name=&quot;minlat&quot; use=&quot;required&quot; type=&quot;{http://www.topografix.com/GPX/1/0}latitudeType&quot; /&gt;
 *       &lt;attribute name=&quot;minlon&quot; use=&quot;required&quot; type=&quot;{http://www.topografix.com/GPX/1/0}longitudeType&quot; /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "boundsType")
@SuppressWarnings("all")
public class BoundsType {

  @XmlAttribute(required = true)
  protected BigDecimal maxlat;

  @XmlAttribute(required = true)
  protected BigDecimal maxlon;

  @XmlAttribute(required = true)
  protected BigDecimal minlat;

  @XmlAttribute(required = true)
  protected BigDecimal minlon;

  /**
   * Gets the value of the maxlat property.
   * 
   * @return possible object is {@link BigDecimal }
   * 
   */
  public BigDecimal getMaxlat() {
    return maxlat;
  }

  /**
   * Sets the value of the maxlat property.
   * 
   * @param value
   *          allowed object is {@link BigDecimal }
   * 
   */
  public void setMaxlat(BigDecimal value) {
    this.maxlat = value;
  }

  /**
   * Gets the value of the maxlon property.
   * 
   * @return possible object is {@link BigDecimal }
   * 
   */
  public BigDecimal getMaxlon() {
    return maxlon;
  }

  /**
   * Sets the value of the maxlon property.
   * 
   * @param value
   *          allowed object is {@link BigDecimal }
   * 
   */
  public void setMaxlon(BigDecimal value) {
    this.maxlon = value;
  }

  /**
   * Gets the value of the minlat property.
   * 
   * @return possible object is {@link BigDecimal }
   * 
   */
  public BigDecimal getMinlat() {
    return minlat;
  }

  /**
   * Sets the value of the minlat property.
   * 
   * @param value
   *          allowed object is {@link BigDecimal }
   * 
   */
  public void setMinlat(BigDecimal value) {
    this.minlat = value;
  }

  /**
   * Gets the value of the minlon property.
   * 
   * @return possible object is {@link BigDecimal }
   * 
   */
  public BigDecimal getMinlon() {
    return minlon;
  }

  /**
   * Sets the value of the minlon property.
   * 
   * @param value
   *          allowed object is {@link BigDecimal }
   * 
   */
  public void setMinlon(BigDecimal value) {
    this.minlon = value;
  }

}
