#!/bin/bash
function compile {
	echo Compiling $1
	msgfmt --statistics --java2 -d ../bin -r org.fibs.geotag.i18n.Messages -l $1 ../i18n/$1.po
	echo
}  

cd ../src
pwd
compile de
compile da
compile fr
compile en_GB
compile nl
compile pt_BR
cd ../i18n
echo Refresh bin folder in Eclipse
